#!/bin/bash
# JOKER BRISCOLA - QUICK START GUIDE

echo "🃏 JOKER BRISCOLA - PREMIUM EDITION"
echo "===================================="
echo ""
echo "📖 COME INIZIARE:"
echo "1. Apri index.html nel browser"
echo "2. Clicca una carta dalla tua mano per giocare"
echo "3. L'IA gioca automaticamente"
echo "4. Clicca 'Prossima Mano' dopo la presa"
echo ""
echo "⚙️ CONFIGURAZIONE:"
echo "   Apri console browser (F12) e digita:"
echo ""
echo "   Preset veloci:"
echo "   - applyPreset('Fully Premium')"
echo "   - applyPreset('Silent Mode')"
echo "   - applyPreset('Performance Mode')"
echo "   - applyPreset('Casual')"
echo ""
echo "   Audio:"
echo "   - toggleAudio()           # Accendi/spegni"
echo "   - setAudioVolume(0.5)     # 50% volume"
echo ""
echo "   Statistiche:"
echo "   - displaySessionStats()   # Mostra stats"
echo "   - exportStats()           # Esporta JSON"
echo "   - getWinRate()            # Win rate %"
echo ""
echo "🎮 COMANDI GIOCO:"
echo "   🔄 Ricomincia      - Button in alto a sinistra"
echo "   📜 Regole          - Visualizza regole"
echo "   📊 Storico         - Prese precedenti"
echo "   ⚙️  Difficoltà      - Scegli livello IA"
echo ""
echo "🎯 LIVELLI IA:"
echo "   🟡 Intermediate    - Semplice, buono per imparare"
echo "   🔴 Hard            - Difficile, analizza scenari"
echo ""
echo "💡 PRO TIPS:"
echo "   • Aspetta animazione prima di giocare carta"
echo "   • Briscola dorata = Joker rivelato"
echo "   • Toast rosso = Mossa illegale"
echo "   • Manda feedback in console se bug!"
echo ""
echo "📱 MOBILE:"
echo "   • Landscape orientation recommended"
echo "   • Touch-friendly interface"
echo "   • Audio disabilitato (clicca per enable)"
echo ""
echo "❓ PROBLEMI?"
echo "   Console (F12):"
echo "   - validateGameState()       # Diagnostica"
echo "   - recoverFromCorruptedState() # Recovery"
echo "   - GAME_STATE               # Debug info"
echo ""
echo "✅ Buon divertimento! 🎉"
